### ISSUE TITLE
Increase payload size

### ISSUE THREAD

**Issue by carlos-mg89** [racemap/elevation-service#10]
Hi again!

I'm getting a great response from the service, although from time to time I get some issues. I'm trying to obtain the elevation for GPX files, to do so, first I parse the GPX, I obtain the latitude and longitude pairs, and write them as a JSON array. And it works very good even for GPX files with several thousands of points.

However, for some files (the one I'm trying right now has 200.000 points), it throws the following error:

HTTP Exception 413 Payload Too Large
Body: (Body exceeded 700kb limit)

The thing is that I have edited the Dockerfile and I set a very large size (700000 kb), which I believe it has to be more than enough. Even for 200.000 points. After editing the file, I have restarted the docker instance, but the result is the same. Could anyone help me here please?

I could obviously proceed in a different way. By sending requests of a maximum of 10.000 points. But, I'd rather do it all at once if it could be possible.

Cheers!

**Comment by carlos-mg89** [comment]
Mmm, the rebuild didn't work due to problems with my main disk. I actually have the elevation data on a regular hard drive, and there's more than enough space there. But I guess that the rebuild, somehow, tries to copy everything through the main partition (which has 84 GB free), and it ends up totally full and throws an error afterwards.

I tried removing the container and the image, and running `docker run --rm -v/media/carlos/Data_3TB/osm/elevation-service/data:/app/data -p3000:3000 normanrz/elevation-service` again, and after pulling the image, it starts the container, but I get the same error again.

I even did a `docker container prune` with no lack either.

It seems pretty strange to me. The Dockerfile is modified on the following line:

ENV MAX_POST_SIZE 700000kb

Perhaps I'm not prunning Docker correctly??? I tried removing the container with `docker rm container_id` too.

**Comment by normanrz** [comment]
You could try rebuilding from a fresh checkout of the repo (without any data in it).
Or you can set the env var upon startup `docker run --rm -e MAX_POST_SIZE=700000kb -v/media/carlos/Data_3TB/osm/elevation-service/data:/app/data -p3000:3000 normanrz/elevation-service`

**Comment by carlos-mg89** [comment]
Something is not working fine. After stopping and then starting the docker machine with the MAX_POST_SIZE=700000kb, the previous error is not being fired, but I obtain an error anyway. However, the error is empty. Cannot figure out right out what error was, even the code, cause the profiler didn't spat that out. The body was empty in this case.

Perhaps it's just too much for a POST request¿? There were ~5 million characters sent in the request.

**Comment by normanrz** [comment]
Hmm. Maybe it would be a good idea to split your requests after all. I haven't tested the service with large payloads.

**Comment by carlos-mg89** [comment]
Thanks for your assistance! I learnt a few things about docker I had no clue about, so at least it was very worthy :)

I'm going to try splitting them and see how it goes. But so far, the results have been pretty good. There are some differences with other services, but they are not that big (1-10%) neither abrupt (which was my main worry).
