### ISSUE TITLE
Getting 502: Bad gateway with elevation.racemap.com/api

### ISSUE THREAD

**Issue by arsenalol69** [racemap/elevation-service#14]
Hi ! Firstly, thank you for your awesome repository :) Nice work !
I wanted to test your api "elevation.racemap.com/api" but it seems that it isn't working at all since a week... I always get an "Error 502 : Bad Gateway".
Exemple of request :
`curl -d '[[51.3, 13.4], [51.4, 13.3]]' -XPOST -H 'Content-Type: application/json' https://elevation.racemap.com/api`

**Comment by normanrz** [comment]
Should be working again. Please note there is a 1 req/s rate limit per ip address.

**Comment by arsenalol69** [comment]
Perfect ! Thanks :)
