### ISSUE TITLE
API gateway timed out 

### ISSUE THREAD

**Issue by RobertMouncer** [racemap/elevation-service#15]
When making an POST or GET request via Postman I recieve a timed out error 😢

**Comment by normanrz** [comment]
The server seems to be overloaded at the moment. I'll implement more aggressive rate-limiting for multi-user fairness. Our server is only really meant for testing the service out. If people like it, they should run the service on their own server for better availability. 

We can also provide dedicated servers for a fee.

**Comment by normanrz** [comment]
The service is available again. Thanks for reporting!
