### ISSUE TITLE
Download set amount of data

### ISSUE THREAD

**Issue by RobertMouncer** [racemap/elevation-service#16]
Great API and we are looking to self host.
Is it possible to download a set amount of data from the S3 server and use the elevation service on that? For example I would just like to download the data for the UK and make a request to that.

**Comment by RobertMouncer** [comment]
Another question about the dataset - are there licensing issues for using it commerically?

**Comment by normanrz** [comment]
You can download portions of the data. The data is organized by latitude/longitude where each chunk is 1x1 degree. For downloading the UK data you need to know the lat/lng extent of the UK and download all the necessary files. Example:
```
aws s3 cp --no-sign-request s3://elevation-tiles-prod/skadi/N51/N51E000.hgt.gz /path/to/data/folder/N51
```
Make sure to reproduce the file structure when downloading, e.g. `./N51/N51E001.hgt.gz`.

The whole dataset is just ~200GB, so maybe it is even feasible to download the whole thing.

Regarding the licensing, please check for yourself: https://registry.opendata.aws/terrain-tiles/ & https://www.mapzen.com/terms/

**Comment by RobertMouncer** [comment]
Thank you very much. 
I'm assuming, because of the 1x1 degree tiles, that the file `N51E001.hgt.gz` contains data from `N51E001 `to `N52E002`

**Comment by normanrz** [comment]
Yes, I believe that is the case.

**Comment by RobertMouncer** [comment]
Python script to download set amount of data from the S3 server:

`import os
latRange = [49,60]
lngRange = [-12,2]
for lat in range(latRange[0], latRange[1]):
	for lng in range(lngRange[0], lngRange[1]):
		latSign = 'N'
		if lat < 0:
			latSign = 'S'
		lngSign = 'E'
		if lng < 0:
			lngSign = 'W'
			
		folder = latSign + str(abs(lat)).zfill(2)
		filename = folder + lngSign + str(abs(lng)).zfill(3)
		destination = "./" + folder + "/" + filename + ".hgt.gz"
		#"s3://elevation-tiles-prod/skadi/N51/N51E000.hgt.gz"
		source = "s3://elevation-tiles-prod/skadi/"+ folder +"/" + filename + ".hgt.gz"
		commands = ["aws s3 cp --no-sign-request", source, destination]
		process = os.system(' '.join(x for x in commands))`
