### ISSUE TITLE
Gap between elevation-service and google maps

### ISSUE THREAD

**Issue by canssens** [racemap/elevation-service#2]
Hello,

Thank you for your fork, i appreciate the easy loading of data with the cache.

I tried with a sample data and i found big gaps versus google elevation api. Do you have an idea of the source of problem?

![image](https://user-images.githubusercontent.com/3133591/43575614-8ee2995a-9647-11e8-818e-8d9766d8ebf7.png)

**Comment by normanrz** [comment]
tbh I'm not sure where those gaps come from. I'm experimenting with a new implementation of the elevation-service. If you find some time, you can try the new service like this:

```bash
# [[lat, lng], ...]
curl -d '[[51.3, 13.4], [51.4, 13.3]]' -H 'Content-Type: application/json' https://elevation.racemap.com/v2
```

**Comment by canssens** [comment]
hello @normanrz ,

Really interesting : 
![image](https://user-images.githubusercontent.com/3133591/43703039-e15461b6-995b-11e8-8926-759908471473.png)

for me it is perfect, good resolution, totally correlated with google maps elevation api. Do you plan to share your new implementation?

**Comment by normanrz** [comment]
Absolutely! The code is already on the `node` branch: https://github.com/normanrz/elevation-service/tree/node
Still pretty barebones. I'm not sure whether I'll make a new repository.

**Comment by normanrz** [comment]
I decided to deprecate the old implementation and promote the new one.
Btw how would you use this service? With downloaded data or with S3? I think this could make a great lambda function, but haven't found the time to set that up.

**Comment by canssens** [comment]
Hello @normanrz sorry i didn't saw your answer before. 
I use it with embeded data in the filesystem, i didn't get great performance with S3 loading.

I did some change for my usage  : 
- add a status page for monitoring + Docker healthcheck
- change the format of answer
input
`
{
	"locations":
	[
		{"latitude": 43.17544,"longitude":5.774021},
{"latitude": 43.17537,"longitude":5.774077},
{"latitude": 43.17539,"longitude":5.774094}	
	]
}`

output
`{
    "results": [
        {
            "latitude": 43.17544,
            "longitude": 5.774021,
            "elevation": 62.61510080001519
        },
        {
            "latitude": 43.17537,
            "longitude": 5.774077,
            "elevation": 62.458860800008644
        },
        {
            "latitude": 43.17539,
            "longitude": 5.774094,
            "elevation": 62.73902720000009
        }
    ]
}`


you can find my fork here : 
https://github.com/canssens/elevation-service/tree/feature/status_and_format_post

If you are interested, i can realize a pull request.

**Comment by normanrz** [comment]
Thanks for sharing your fork!
I'd be happy to include the healthcheck. I'm not keen on changing the API, though.

**Comment by zstadler** [comment]
@normanrz and @canssens 
It seems like all aspects if this issue have been addressed more than 3 years ago.
Shouldn't this issue be closed?
