### ISSUE TITLE
POST not working in https://elevation.racemap.com/api

### ISSUE THREAD

**Issue by jjimenezshaw** [racemap/elevation-service#6]
I am trying to do a POST request (with a few points) to https://elevation.racemap.com/api, and I get an Error 405. Is POST enabled?

**Comment by normanrz** [comment]
This works for me:

`curl -d '[[51.3, 13.4], [51.4, 13.3]]' -XPOST -H 'Content-Type: application/json' https://elevation.racemap.com/api`

**Comment by jjimenezshaw** [comment]
I am calling from Javascript.
I get exactly this:

```
OPTIONS https://elevation.racemap.com/api 405 (twice)

Access to fetch at 'https://elevation.racemap.com/api' from origin 'http://mini' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
```

when I call with:

        fetch('https://elevation.racemap.com/api', {
            method: 'POST',
            body: objStr,
            headers:{
                'Content-Type': 'application/json',
                'Accept': 'application/json',
            }
        })
        .then(response => {
            return response.json();
        })

**Comment by normanrz** [comment]
Ah, I see. I'll fix the cors issue.

**Comment by normanrz** [comment]
Fixed in https://github.com/racemap/elevation-service/commit/3e7625837997bc213f03e02e4cb54831088e5cd4. Can you please try again now?

**Comment by jjimenezshaw** [comment]
Now works! Thanks.
