### ISSUE TITLE
Cost of downloading from AWS S3

### ISSUE THREAD

**Issue by carlos-mg89** [racemap/elevation-service#8]
I don't know about the cost of downloading the data with AWS S3. If it has a cost, is there any free alternative?

Aside from this, I run `aws s3 cp --recursive s3://elevation-tiles-prod/skadi data` and it return "fatal error: Unable to locate credentials", which I believe implies I need to use credentials from an Amazon AWS account in order to download the data. So I believe it will imply an economic cost.

Thanks in advance!

**Comment by normanrz** [comment]
Should we add `--no-sign-request` to the readme then?

**Comment by carlos-mg89** [comment]
Great @mtmail ! It's downloading already :) And actually, that's a ridiculous price. But it's even better that there's no need for the downloaders to pay for this very important data.

Will test how is the quality of the data, but for what I've read, it looks promising!
